# Generated by Django 4.2.7 on 2023-11-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
